// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:81bf86d2-3954-4130-9257-8df4173e9b5b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8wLXT2Lkx",
    "aws_user_pools_web_client_id": "1bh0a77gqdns8qm5ln5nohpkaj",
    "oauth": {}
};


export default awsmobile;
